FROM node:15.4 as build
WORKDIR /app
COPY package.json yarn.lock /app/
RUN yarn
COPY . .
RUN yarn build

FROM node:15.4
WORKDIR /app
COPY package.json yarn.lock
RUN yarn --only=production
COPY --from=build /app/dist ./dist
CMD yarn start: prod